n = str(input('Digite seu Nome Completo: '))
nma = n.upper()
nme = n.lower()
nldpn = n.split()
nldpn1 = len(nldpn[0][0:])
ndlse = len(n) - n.count(' ') 
print('Seu Nome Totalmente Maiusculo é: {} \nSeu Nome Totalmente Menosculo é: {}\nO total De letras do seu nome é: {} \nA Primeira Palavra do Seu Nome tem {} Letras'.format(nma,nme,ndlse,nldpn1))