n = str(input('Digite seu Nome Completo: '))
nma = n.upper()
nme = n.lower()
nldpn = n.split()
nldpn1 = len(nldpn[0][0:])
ndlse = n.split() 
print('Seu Nome Totalmente Maiusculo é: {} \nSeu Nome Totalmente Menosculo é: {} \nA Primeira Palavra do Seu Nome tem {} Letras'.format(nma,nme,nldpn1))
print(len(ndlse[0:]).)